; ==================================================
; 红警INI片段精炼厂 - 心灵终结时静光照
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[Triggers]
01TIME01=Neutral,<none>,[TIMEFREEZE] Detect ON,1,1,1,1,0
01TIME03=Neutral,<none>,[TIMEFREEZE] Detect OFF,1,1,1,1,0
01TIME05=Neutral,<none>,[TIMEFREEZE] Process ON - Lighting,1,1,1,1,0
01TIME07=Neutral,<none>,[TIMEFREEZE] Process OFF - Lighting,1,1,1,1,0
01TIME09=Neutral,<none>,[TIMEFREEZE] Process ON - Lighting Bright 1,0,1,1,1,0
01TIME11=Neutral,<none>,[TIMEFREEZE] Process ON - Lighting Bright 2,0,1,1,1,0
01TIME13=Neutral,<none>,[TIMEFREEZE] Process ON - Lighting Bright 3,0,1,1,1,0
01TIME15=Neutral,<none>,[TIMEFREEZE] Process ON - Lighting Bright 4,0,1,1,1,0
01TIME17=Neutral,<none>,[TIMEFREEZE] Process ON - Lighting Bright 5,0,1,1,1,0
01TIME19=Neutral,<none>,[TIMEFREEZE] Process ON - Lighting Bright 6,0,1,1,1,0
01TIME21=Neutral,<none>,[TIMEFREEZE] Process ON - Lighting Bright 7,0,1,1,1,0
01TIME23=Neutral,<none>,[TIMEFREEZE] Process ON - Lighting Bright 8,0,1,1,1,0
01TIME25=Neutral,<none>,[TIMEFREEZE] Process ON - Lighting Bright 9,0,1,1,1,0
01TIME27=Neutral,<none>,[TIMEFREEZE] Process ON - Lighting Bright 10,0,1,1,1,0
[Tags]
01TIME00=2,[TIMEFREEZE] Detect ON 1,01TIME01
01TIME02=2,[TIMEFREEZE] Detect OFF 1,01TIME03
01TIME04=2,[TIMEFREEZE] Process ON - Lighting 1,01TIME05
01TIME06=2,[TIMEFREEZE] Process OFF - Lighting 1,01TIME07
01TIME08=2,[TIMEFREEZE] Process ON - Lighting Bright 1 1,01TIME09
01TIME10=2,[TIMEFREEZE] Process ON - Lighting Bright 2 1,01TIME11
01TIME12=2,[TIMEFREEZE] Process ON - Lighting Bright 3 1,01TIME13
01TIME14=2,[TIMEFREEZE] Process ON - Lighting Bright 4 1,01TIME15
01TIME16=2,[TIMEFREEZE] Process ON - Lighting Bright 5 1,01TIME17
01TIME18=2,[TIMEFREEZE] Process ON - Lighting Bright 6 1,01TIME19
01TIME20=2,[TIMEFREEZE] Process ON - Lighting Bright 7 1,01TIME21
01TIME22=2,[TIMEFREEZE] Process ON - Lighting Bright 8 1,01TIME23
01TIME24=2,[TIMEFREEZE] Process ON - Lighting Bright 9 1,01TIME25
01TIME26=2,[TIMEFREEZE] Process ON - Lighting Bright 10 1,01TIME27
[Events]
01TIME01=1,8,0,20
01TIME03=1,8,0,20
01TIME05=1,36,0,60
01TIME07=1,13,0,0
01TIME09=2,51,0,5,36,0,60
01TIME11=2,51,0,5,36,0,60
01TIME13=2,51,0,5,36,0,60
01TIME15=2,51,0,5,36,0,60
01TIME17=2,51,0,5,36,0,60
01TIME19=2,51,0,5,36,0,60
01TIME21=2,51,0,5,36,0,60
01TIME23=2,51,0,5,36,0,60
01TIME25=2,51,0,5,36,0,60
01TIME27=2,51,0,5,36,0,60
[Actions]
01TIME01=3,54,2,01TIME01,0,0,0,0,A,53,2,01TIME05,0,0,0,0,A,56,0,60,0,0,0,0,A
01TIME03=3,54,2,01TIME03,0,0,0,0,A,53,2,01TIME07,0,0,0,0,A,57,0,60,0,0,0,0,A
01TIME05=4,54,2,01TIME05,0,0,0,0,A,142,0,50,0,0,0,0,A,143,0,50,0,0,0,0,A,144,0,50,0,0,0,0,A
01TIME07=5,54,2,01TIME07,0,0,0,0,A,142,0,75,0,0,0,0,A,143,0,55,0,0,0,0,A,144,0,95,0,0,0,0,A,73,0,105,0,0,0,0,A
01TIME09=1,73,0,95,0,0,0,0,A
01TIME11=1,73,0,92,0,0,0,0,A
01TIME13=1,73,0,89,0,0,0,0,A
01TIME15=1,73,0,87,0,0,0,0,A
01TIME17=1,73,0,85,0,0,0,0,A
01TIME19=1,73,0,83,0,0,0,0,A
01TIME21=1,73,0,81,0,0,0,0,A
01TIME23=1,73,0,79,0,0,0,0,A
01TIME25=1,73,0,77,0,0,0,0,A
01TIME27=1,73,0,75,0,0,0,0,A
[VariableNames]
60=TimeFreeze Light,0