; ==================================================
; 红警INI片段百宝箱 - 玛雅金字塔加强debug（测图专用，挡电脑进攻）
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[MAYAN]
Strength=10000
[MayanPrism]
Damage=1000
ROF=1
Range=30
Speed=25
Projectile=Invisible3