; ==================================================
; 红色警戒2 INI片段精炼厂
; 创建者：cake1 (https://github.com/GlowingCake/-RA2-INI_For_Mappers)
; 许可证：MIT
; ==================================================

[MAYAN]
Strength=10000
[MayanPrism]
Damage=1000
ROF=1
Range=30
Speed=25
Projectile=Invisible3