; ==================================================
; 红警INI片段百宝箱 - 禁止初始部队（无论玩家如何设置，都不刷初始兵和坦克）
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[E1]
AllowedToStartInMultiplayer=no
[E2]
AllowedToStartInMultiplayer=no
[HTNK]
AllowedToStartInMultiplayer=no
[INIT]
AllowedToStartInMultiplayer=no
[LTNK]
AllowedToStartInMultiplayer=no
[MTNK]
AllowedToStartInMultiplayer=no