; ==================================================
; 红警INI片段精炼厂 - 虚拟金钱建筑（注册获得时给钱的空建筑，按需给予玩家即可）
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[BuildingTypes]
1000=CASHGIVE;虚拟给钱
1001=CASHTAKE;虚拟扣钱
1002=CANOTHING;用于触发的承载建筑，例如检测玩家进入或死亡
[CASHGIVE]
Name=Dummy Cash Give
;UIName=
TechLevel=-1
Strength=1000
Insignificant=yes
Nominal=yes
;RadarInvisible=yes
Points=0
Armor=wood
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=0
BaseNormal=no
Sight=0 ; UC base values
ClickRepairable=no
Immune=yes
ProduceCashStartup=10000
[CASHTAKE]
Name=Dummy Cash Take
;UIName=
TechLevel=-1
Strength=1000
Insignificant=yes
Nominal=yes
;RadarInvisible=yes
Points=0
Armor=wood
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=0
BaseNormal=no
Sight=0 ; UC base values
ClickRepairable=no
Immune=yes
ProduceCashStartup=-10000
[CANOTHING]
Name=Dummy Nothing Building
;UIName=
TechLevel=-1
Strength=1000
Insignificant=yes
Nominal=yes
;RadarInvisible=yes
Points=0
Armor=wood
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=0
BaseNormal=no
Sight=0 ; UC base values
ClickRepairable=no
Immune=yes