; ==================================================
; 红色警戒2 INI片段精炼厂 - 复活作战小队片段
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[TaskForces]
200=RSTF_DF
[ScriptTypes]
0=RSST_DF
[RSST_DF]
0=0,1
Name=[Respawn]Default
[RSTF_DF]
0=2,E1
Name=[Respawn]Default
Group=-1

[Actions]
RS10001=2,54,2,RS10001,0,0,0,0,A,7,1,RST1001,0,0,0,0,A
RS10002=1,53,2,RS10001,0,0,0,0,A
RS20001=2,54,2,RS20001,0,0,0,0,A,7,1,RST2001,0,0,0,0,A
RS20002=1,53,2,RS20001,0,0,0,0,A
RS30001=2,54,2,RS30001,0,0,0,0,A,7,1,RST3001,0,0,0,0,A
RS30002=1,53,2,RS30001,0,0,0,0,A
RS40001=2,54,2,RS40001,0,0,0,0,A,7,1,RST4001,0,0,0,0,A
RS40002=1,53,2,RS40001,0,0,0,0,A
RS50001=2,54,2,RS50001,0,0,0,0,A,7,1,RST5001,0,0,0,0,A
RS50002=1,53,2,RS50001,0,0,0,0,A
RS60001=2,54,2,RS60001,0,0,0,0,A,7,1,RST6001,0,0,0,0,A
RS60002=1,53,2,RS60001,0,0,0,0,A
RS70001=2,54,2,RS70001,0,0,0,0,A,7,1,RST7001,0,0,0,0,A
RS70002=1,53,2,RS70001,0,0,0,0,A
RS80001=2,54,2,RS80001,0,0,0,0,A,7,1,RST8001,0,0,0,0,A
RS80002=1,53,2,RS80001,0,0,0,0,A
RS90001=2,54,2,RS90001,0,0,0,0,A,7,1,RST9001,0,0,0,0,A
RS90002=1,53,2,RS90001,0,0,0,0,A
RS100001=2,54,2,RS100001,0,0,0,0,A,7,1,RST10001,0,0,0,0,A
RS100002=1,53,2,RS100001,0,0,0,0,A

[Events]
RS10001=1,13,0,10
RS10002=1,48,0,0
RS20001=1,13,0,10
RS20002=1,48,0,0
RS30001=1,13,0,10
RS30002=1,48,0,0
RS40001=1,13,0,10
RS40002=1,48,0,0
RS50001=1,13,0,10
RS50002=1,48,0,0
RS60001=1,13,0,10
RS60002=1,48,0,0
RS70001=1,13,0,10
RS70002=1,48,0,0
RS80001=1,13,0,10
RS80002=1,48,0,0
RS90001=1,13,0,10
RS90002=1,48,0,0
RS100001=1,13,0,10
RS100002=1,48,0,0

[Tags]
RS10001_tag=2,[Respawn_Team]Creat No .1 1,RS10001
RS10002_tag=1,[Respawn_Detect]No .1 1,RS10002
RS20001_tag=2,[Respawn_Team]Creat No .2 1,RS20001
RS20002_tag=1,[Respawn_Detect]No .2 1,RS20002
RS30001_tag=2,[Respawn_Team]Creat No .3 1,RS30001
RS30002_tag=1,[Respawn_Detect]No .3 1,RS30002
RS40001_tag=2,[Respawn_Team]Creat No .4 1,RS40001
RS40002_tag=1,[Respawn_Detect]No .4 1,RS40002
RS50001_tag=2,[Respawn_Team]Creat No .5 1,RS50001
RS50002_tag=1,[Respawn_Detect]No .5 1,RS50002
RS60001_tag=2,[Respawn_Team]Creat No .6 1,RS60001
RS60002_tag=1,[Respawn_Detect]No .6 1,RS60002
RS70001_tag=2,[Respawn_Team]Creat No .7 1,RS70001
RS70002_tag=1,[Respawn_Detect]No .7 1,RS70002
RS80001_tag=2,[Respawn_Team]Creat No .8 1,RS80001
RS80002_tag=1,[Respawn_Detect]No .8 1,RS80002
RS90001_tag=2,[Respawn_Team]Creat No .9 1,RS90001
RS90002_tag=1,[Respawn_Detect]No .9 1,RS90002
RS100001_tag=2,[Respawn_Team]Creat No .10 1,RS100001
RS100002_tag=1,[Respawn_Detect]No .10 1,RS100002

[Triggers]
RS10001=Americans,<none>,[Respawn_Team]Creat No .1,1,1,1,1,0
RS10002=Americans,<none>,[Respawn_Detect]No .1,0,1,1,1,0
RS20001=Americans,<none>,[Respawn_Team]Creat No .2,1,1,1,1,0
RS20002=Americans,<none>,[Respawn_Detect]No .2,0,1,1,1,0
RS30001=Americans,<none>,[Respawn_Team]Creat No .3,1,1,1,1,0
RS30002=Americans,<none>,[Respawn_Detect]No .3,0,1,1,1,0
RS40001=Americans,<none>,[Respawn_Team]Creat No .4,1,1,1,1,0
RS40002=Americans,<none>,[Respawn_Detect]No .4,0,1,1,1,0
RS50001=Americans,<none>,[Respawn_Team]Creat No .5,1,1,1,1,0
RS50002=Americans,<none>,[Respawn_Detect]No .5,0,1,1,1,0
RS60001=Americans,<none>,[Respawn_Team]Creat No .6,1,1,1,1,0
RS60002=Americans,<none>,[Respawn_Detect]No .6,0,1,1,1,0
RS70001=Americans,<none>,[Respawn_Team]Creat No .7,1,1,1,1,0
RS70002=Americans,<none>,[Respawn_Detect]No .7,0,1,1,1,0
RS80001=Americans,<none>,[Respawn_Team]Creat No .8,1,1,1,1,0
RS80002=Americans,<none>,[Respawn_Detect]No .8,0,1,1,1,0
RS90001=Americans,<none>,[Respawn_Team]Creat No .9,1,1,1,1,0
RS90002=Americans,<none>,[Respawn_Detect]No .9,0,1,1,1,0
RS100001=Americans,<none>,[Respawn_Team]Creat No .10,1,1,1,1,0
RS100002=Americans,<none>,[Respawn_Detect]No .10,0,1,1,1,0

[TeamTypes]
200=RST1001
201=RST2001
202=RST3001
203=RST4001
204=RST5001
205=RST6001
206=RST7001
207=RST8001
208=RST9001
209=RST10001

[RST1001]
Max=5
Tag=RS10002_tag
Full=no
Name=[Respawn]No.1
Group=-1
House=<Player @ A>
Script=RSST_DF
Whiner=no
Droppod=no
Suicide=no
Loadable=no
Prebuild=no
Priority=5
Waypoint=HZ
Annoyance=no
IonImmune=no
Recruiter=no
Reinforce=no
TaskForce=RSTF_DF
TechLevel=0
Aggressive=no
Autocreate=no
GuardSlower=no
OnTransOnly=no
AvoidThreats=no
LooseRecruit=no
VeteranLevel=1
IsBaseDefense=no
UseTransportOrigin=no
MindControlDecision=0
OnlyTargetHouseEnemy=no
TransportsReturnOnUnload=no
AreTeamMembersRecruitable=no

[RST2001]
Max=5
Tag=RS20002_tag
Full=no
Name=[Respawn]No.2
Group=-1
House=<Player @ A>
Script=RSST_DF
Whiner=no
Droppod=no
Suicide=no
Loadable=no
Prebuild=no
Priority=5
Waypoint=HZ
Annoyance=no
IonImmune=no
Recruiter=no
Reinforce=no
TaskForce=RSTF_DF
TechLevel=0
Aggressive=no
Autocreate=no
GuardSlower=no
OnTransOnly=no
AvoidThreats=no
LooseRecruit=no
VeteranLevel=1
IsBaseDefense=no
UseTransportOrigin=no
MindControlDecision=0
OnlyTargetHouseEnemy=no
TransportsReturnOnUnload=no
AreTeamMembersRecruitable=no

[RST3001]
Max=5
Tag=RS30002_tag
Full=no
Name=[Respawn]No.3
Group=-1
House=<Player @ A>
Script=RSST_DF
Whiner=no
Droppod=no
Suicide=no
Loadable=no
Prebuild=no
Priority=5
Waypoint=HZ
Annoyance=no
IonImmune=no
Recruiter=no
Reinforce=no
TaskForce=RSTF_DF
TechLevel=0
Aggressive=no
Autocreate=no
GuardSlower=no
OnTransOnly=no
AvoidThreats=no
LooseRecruit=no
VeteranLevel=1
IsBaseDefense=no
UseTransportOrigin=no
MindControlDecision=0
OnlyTargetHouseEnemy=no
TransportsReturnOnUnload=no
AreTeamMembersRecruitable=no

[RST4001]
Max=5
Tag=RS40002_tag
Full=no
Name=[Respawn]No.4
Group=-1
House=<Player @ A>
Script=RSST_DF
Whiner=no
Droppod=no
Suicide=no
Loadable=no
Prebuild=no
Priority=5
Waypoint=HZ
Annoyance=no
IonImmune=no
Recruiter=no
Reinforce=no
TaskForce=RSTF_DF
TechLevel=0
Aggressive=no
Autocreate=no
GuardSlower=no
OnTransOnly=no
AvoidThreats=no
LooseRecruit=no
VeteranLevel=1
IsBaseDefense=no
UseTransportOrigin=no
MindControlDecision=0
OnlyTargetHouseEnemy=no
TransportsReturnOnUnload=no
AreTeamMembersRecruitable=no

[RST5001]
Max=5
Tag=RS50002_tag
Full=no
Name=[Respawn]No.5
Group=-1
House=<Player @ A>
Script=RSST_DF
Whiner=no
Droppod=no
Suicide=no
Loadable=no
Prebuild=no
Priority=5
Waypoint=HZ
Annoyance=no
IonImmune=no
Recruiter=no
Reinforce=no
TaskForce=RSTF_DF
TechLevel=0
Aggressive=no
Autocreate=no
GuardSlower=no
OnTransOnly=no
AvoidThreats=no
LooseRecruit=no
VeteranLevel=1
IsBaseDefense=no
UseTransportOrigin=no
MindControlDecision=0
OnlyTargetHouseEnemy=no
TransportsReturnOnUnload=no
AreTeamMembersRecruitable=no

[RST6001]
Max=5
Tag=RS60002_tag
Full=no
Name=[Respawn]No.6
Group=-1
House=<Player @ A>
Script=RSST_DF
Whiner=no
Droppod=no
Suicide=no
Loadable=no
Prebuild=no
Priority=5
Waypoint=HZ
Annoyance=no
IonImmune=no
Recruiter=no
Reinforce=no
TaskForce=RSTF_DF
TechLevel=0
Aggressive=no
Autocreate=no
GuardSlower=no
OnTransOnly=no
AvoidThreats=no
LooseRecruit=no
VeteranLevel=1
IsBaseDefense=no
UseTransportOrigin=no
MindControlDecision=0
OnlyTargetHouseEnemy=no
TransportsReturnOnUnload=no
AreTeamMembersRecruitable=no

[RST7001]
Max=5
Tag=RS70002_tag
Full=no
Name=[Respawn]No.7
Group=-1
House=<Player @ A>
Script=RSST_DF
Whiner=no
Droppod=no
Suicide=no
Loadable=no
Prebuild=no
Priority=5
Waypoint=HZ
Annoyance=no
IonImmune=no
Recruiter=no
Reinforce=no
TaskForce=RSTF_DF
TechLevel=0
Aggressive=no
Autocreate=no
GuardSlower=no
OnTransOnly=no
AvoidThreats=no
LooseRecruit=no
VeteranLevel=1
IsBaseDefense=no
UseTransportOrigin=no
MindControlDecision=0
OnlyTargetHouseEnemy=no
TransportsReturnOnUnload=no
AreTeamMembersRecruitable=no

[RST8001]
Max=5
Tag=RS80002_tag
Full=no
Name=[Respawn]No.8
Group=-1
House=<Player @ A>
Script=RSST_DF
Whiner=no
Droppod=no
Suicide=no
Loadable=no
Prebuild=no
Priority=5
Waypoint=HZ
Annoyance=no
IonImmune=no
Recruiter=no
Reinforce=no
TaskForce=RSTF_DF
TechLevel=0
Aggressive=no
Autocreate=no
GuardSlower=no
OnTransOnly=no
AvoidThreats=no
LooseRecruit=no
VeteranLevel=1
IsBaseDefense=no
UseTransportOrigin=no
MindControlDecision=0
OnlyTargetHouseEnemy=no
TransportsReturnOnUnload=no
AreTeamMembersRecruitable=no

[RST9001]
Max=5
Tag=RS90002_tag
Full=no
Name=[Respawn]No.9
Group=-1
House=<Player @ A>
Script=RSST_DF
Whiner=no
Droppod=no
Suicide=no
Loadable=no
Prebuild=no
Priority=5
Waypoint=HZ
Annoyance=no
IonImmune=no
Recruiter=no
Reinforce=no
TaskForce=RSTF_DF
TechLevel=0
Aggressive=no
Autocreate=no
GuardSlower=no
OnTransOnly=no
AvoidThreats=no
LooseRecruit=no
VeteranLevel=1
IsBaseDefense=no
UseTransportOrigin=no
MindControlDecision=0
OnlyTargetHouseEnemy=no
TransportsReturnOnUnload=no
AreTeamMembersRecruitable=no

[RST10001]
Max=5
Tag=RS100002_tag
Full=no
Name=[Respawn]No.10
Group=-1
House=<Player @ A>
Script=RSST_DF
Whiner=no
Droppod=no
Suicide=no
Loadable=no
Prebuild=no
Priority=5
Waypoint=HZ
Annoyance=no
IonImmune=no
Recruiter=no
Reinforce=no
TaskForce=RSTF_DF
TechLevel=0
Aggressive=no
Autocreate=no
GuardSlower=no
OnTransOnly=no
AvoidThreats=no
LooseRecruit=no
VeteranLevel=1
IsBaseDefense=no
UseTransportOrigin=no
MindControlDecision=0
OnlyTargetHouseEnemy=no
TransportsReturnOnUnload=no
AreTeamMembersRecruitable=no

;下方为10~20的部分,如有需要可取消注释
;
;[Actions]
;RS110001=2,54,2,RS110001,0,0,0,0,A,7,1,RST11001,0,0,0,0,A
;RS110002=1,53,2,RS110001,0,0,0,0,A
;RS120001=2,54,2,RS120001,0,0,0,0,A,7,1,RST12001,0,0,0,0,A
;RS120002=1,53,2,RS120001,0,0,0,0,A
;RS130001=2,54,2,RS130001,0,0,0,0,A,7,1,RST13001,0,0,0,0,A
;RS130002=1,53,2,RS130001,0,0,0,0,A
;RS140001=2,54,2,RS140001,0,0,0,0,A,7,1,RST14001,0,0,0,0,A
;RS140002=1,53,2,RS140001,0,0,0,0,A
;RS150001=2,54,2,RS150001,0,0,0,0,A,7,1,RST15001,0,0,0,0,A
;RS150002=1,53,2,RS150001,0,0,0,0,A
;RS160001=2,54,2,RS160001,0,0,0,0,A,7,1,RST16001,0,0,0,0,A
;RS160002=1,53,2,RS160001,0,0,0,0,A
;RS170001=2,54,2,RS170001,0,0,0,0,A,7,1,RST17001,0,0,0,0,A
;RS170002=1,53,2,RS170001,0,0,0,0,A
;RS180001=2,54,2,RS180001,0,0,0,0,A,7,1,RST18001,0,0,0,0,A
;RS180002=1,53,2,RS180001,0,0,0,0,A
;RS190001=2,54,2,RS190001,0,0,0,0,A,7,1,RST19001,0,0,0,0,A
;RS190002=1,53,2,RS190001,0,0,0,0,A
;RS200001=2,54,2,RS200001,0,0,0,0,A,7,1,RST20001,0,0,0,0,A
;RS200002=1,53,2,RS200001,0,0,0,0,A
;
;[Events]
;RS110001=1,13,0,10
;RS110002=1,48,0,0
;RS120001=1,13,0,10
;RS120002=1,48,0,0
;RS130001=1,13,0,10
;RS130002=1,48,0,0
;RS140001=1,13,0,10
;RS140002=1,48,0,0
;RS150001=1,13,0,10
;RS150002=1,48,0,0
;RS160001=1,13,0,10
;RS160002=1,48,0,0
;RS170001=1,13,0,10
;RS170002=1,48,0,0
;RS180001=1,13,0,10
;RS180002=1,48,0,0
;RS190001=1,13,0,10
;RS190002=1,48,0,0
;RS200001=1,13,0,10
;RS200002=1,48,0,0
;
;[Tags]
;RS110001_tag=2,[Respawn_Team]Creat No .11 1,RS110001
;RS110002_tag=1,[Respawn_Detect]No .11 1,RS110002
;RS120001_tag=2,[Respawn_Team]Creat No .12 1,RS120001
;RS120002_tag=1,[Respawn_Detect]No .12 1,RS120002
;RS130001_tag=2,[Respawn_Team]Creat No .13 1,RS130001
;RS130002_tag=1,[Respawn_Detect]No .13 1,RS130002
;RS140001_tag=2,[Respawn_Team]Creat No .14 1,RS140001
;RS140002_tag=1,[Respawn_Detect]No .14 1,RS140002
;RS150001_tag=2,[Respawn_Team]Creat No .15 1,RS150001
;RS150002_tag=1,[Respawn_Detect]No .15 1,RS150002
;RS160001_tag=2,[Respawn_Team]Creat No .16 1,RS160001
;RS160002_tag=1,[Respawn_Detect]No .16 1,RS160002
;RS170001_tag=2,[Respawn_Team]Creat No .17 1,RS170001
;RS170002_tag=1,[Respawn_Detect]No .17 1,RS170002
;RS180001_tag=2,[Respawn_Team]Creat No .18 1,RS180001
;RS180002_tag=1,[Respawn_Detect]No .18 1,RS180002
;RS190001_tag=2,[Respawn_Team]Creat No .19 1,RS190001
;RS190002_tag=1,[Respawn_Detect]No .19 1,RS190002
;RS200001_tag=2,[Respawn_Team]Creat No .20 1,RS200001
;RS200002_tag=1,[Respawn_Detect]No .20 1,RS200002
;
;[Triggers]
;RS110001=Americans,<none>,[Respawn_Team]Creat No .11,1,1,1,1,0
;RS110002=Americans,<none>,[Respawn_Detect]No .11,0,1,1,1,0
;RS120001=Americans,<none>,[Respawn_Team]Creat No .12,1,1,1,1,0
;RS120002=Americans,<none>,[Respawn_Detect]No .12,0,1,1,1,0
;RS130001=Americans,<none>,[Respawn_Team]Creat No .13,1,1,1,1,0
;RS130002=Americans,<none>,[Respawn_Detect]No .13,0,1,1,1,0
;RS140001=Americans,<none>,[Respawn_Team]Creat No .14,1,1,1,1,0
;RS140002=Americans,<none>,[Respawn_Detect]No .14,0,1,1,1,0
;RS150001=Americans,<none>,[Respawn_Team]Creat No .15,1,1,1,1,0
;RS150002=Americans,<none>,[Respawn_Detect]No .15,0,1,1,1,0
;RS160001=Americans,<none>,[Respawn_Team]Creat No .16,1,1,1,1,0
;RS160002=Americans,<none>,[Respawn_Detect]No .16,0,1,1,1,0
;RS170001=Americans,<none>,[Respawn_Team]Creat No .17,1,1,1,1,0
;RS170002=Americans,<none>,[Respawn_Detect]No .17,0,1,1,1,0
;RS180001=Americans,<none>,[Respawn_Team]Creat No .18,1,1,1,1,0
;RS180002=Americans,<none>,[Respawn_Detect]No .18,0,1,1,1,0
;RS190001=Americans,<none>,[Respawn_Team]Creat No .19,1,1,1,1,0
;RS190002=Americans,<none>,[Respawn_Detect]No .19,0,1,1,1,0
;RS200001=Americans,<none>,[Respawn_Team]Creat No .20,1,1,1,1,0
;RS200002=Americans,<none>,[Respawn_Detect]No .20,0,1,1,1,0
;
;[TeamTypes]
;300=RST11001
;301=RST12001
;302=RST13001
;303=RST14001
;304=RST15001
;305=RST16001
;306=RST17001
;307=RST18001
;308=RST19001
;309=RST20001
;
;[RST11001]
;Max=5
;Tag=RS110002_tag
;Full=no
;Name=[Respawn]No.11
;Group=-1
;House=<Player @ A>
;Script=RSST_DF
;Whiner=no
;Droppod=no
;Suicide=no
;Loadable=no
;Prebuild=no
;Priority=5
;Waypoint=HZ
;Annoyance=no
;IonImmune=no
;Recruiter=no
;Reinforce=no
;TaskForce=RSTF_DF
;TechLevel=0
;Aggressive=no
;Autocreate=no
;GuardSlower=no
;OnTransOnly=no
;AvoidThreats=no
;LooseRecruit=no
;VeteranLevel=1
;IsBaseDefense=no
;UseTransportOrigin=no
;MindControlDecision=0
;OnlyTargetHouseEnemy=no
;TransportsReturnOnUnload=no
;AreTeamMembersRecruitable=no
;
;[RST12001]
;Max=5
;Tag=RS120002_tag
;Full=no
;Name=[Respawn]No.12
;Group=-1
;House=<Player @ A>
;Script=RSST_DF
;Whiner=no
;Droppod=no
;Suicide=no
;Loadable=no
;Prebuild=no
;Priority=5
;Waypoint=HZ
;Annoyance=no
;IonImmune=no
;Recruiter=no
;Reinforce=no
;TaskForce=RSTF_DF
;TechLevel=0
;Aggressive=no
;Autocreate=no
;GuardSlower=no
;OnTransOnly=no
;AvoidThreats=no
;LooseRecruit=no
;VeteranLevel=1
;IsBaseDefense=no
;UseTransportOrigin=no
;MindControlDecision=0
;OnlyTargetHouseEnemy=no
;TransportsReturnOnUnload=no
;AreTeamMembersRecruitable=no
;
;[RST13001]
;Max=5
;Tag=RS130002_tag
;Full=no
;Name=[Respawn]No.13
;Group=-1
;House=<Player @ A>
;Script=RSST_DF
;Whiner=no
;Droppod=no
;Suicide=no
;Loadable=no
;Prebuild=no
;Priority=5
;Waypoint=HZ
;Annoyance=no
;IonImmune=no
;Recruiter=no
;Reinforce=no
;TaskForce=RSTF_DF
;TechLevel=0
;Aggressive=no
;Autocreate=no
;GuardSlower=no
;OnTransOnly=no
;AvoidThreats=no
;LooseRecruit=no
;VeteranLevel=1
;IsBaseDefense=no
;UseTransportOrigin=no
;MindControlDecision=0
;OnlyTargetHouseEnemy=no
;TransportsReturnOnUnload=no
;AreTeamMembersRecruitable=no
;
;[RST14001]
;Max=5
;Tag=RS140002_tag
;Full=no
;Name=[Respawn]No.14
;Group=-1
;House=<Player @ A>
;Script=RSST_DF
;Whiner=no
;Droppod=no
;Suicide=no
;Loadable=no
;Prebuild=no
;Priority=5
;Waypoint=HZ
;Annoyance=no
;IonImmune=no
;Recruiter=no
;Reinforce=no
;TaskForce=RSTF_DF
;TechLevel=0
;Aggressive=no
;Autocreate=no
;GuardSlower=no
;OnTransOnly=no
;AvoidThreats=no
;LooseRecruit=no
;VeteranLevel=1
;IsBaseDefense=no
;UseTransportOrigin=no
;MindControlDecision=0
;OnlyTargetHouseEnemy=no
;TransportsReturnOnUnload=no
;AreTeamMembersRecruitable=no
;
;[RST15001]
;Max=5
;Tag=RS150002_tag
;Full=no
;Name=[Respawn]No.15
;Group=-1
;House=<Player @ A>
;Script=RSST_DF
;Whiner=no
;Droppod=no
;Suicide=no
;Loadable=no
;Prebuild=no
;Priority=5
;Waypoint=HZ
;Annoyance=no
;IonImmune=no
;Recruiter=no
;Reinforce=no
;TaskForce=RSTF_DF
;TechLevel=0
;Aggressive=no
;Autocreate=no
;GuardSlower=no
;OnTransOnly=no
;AvoidThreats=no
;LooseRecruit=no
;VeteranLevel=1
;IsBaseDefense=no
;UseTransportOrigin=no
;MindControlDecision=0
;OnlyTargetHouseEnemy=no
;TransportsReturnOnUnload=no
;AreTeamMembersRecruitable=no
;
;[RST16001]
;Max=5
;Tag=RS160002_tag
;Full=no
;Name=[Respawn]No.16
;Group=-1
;House=<Player @ A>
;Script=RSST_DF
;Whiner=no
;Droppod=no
;Suicide=no
;Loadable=no
;Prebuild=no
;Priority=5
;Waypoint=HZ
;Annoyance=no
;IonImmune=no
;Recruiter=no
;Reinforce=no
;TaskForce=RSTF_DF
;TechLevel=0
;Aggressive=no
;Autocreate=no
;GuardSlower=no
;OnTransOnly=no
;AvoidThreats=no
;LooseRecruit=no
;VeteranLevel=1
;IsBaseDefense=no
;UseTransportOrigin=no
;MindControlDecision=0
;OnlyTargetHouseEnemy=no
;TransportsReturnOnUnload=no
;AreTeamMembersRecruitable=no
;
;[RST17001]
;Max=5
;Tag=RS170002_tag
;Full=no
;Name=[Respawn]No.17
;Group=-1
;House=<Player @ A>
;Script=RSST_DF
;Whiner=no
;Droppod=no
;Suicide=no
;Loadable=no
;Prebuild=no
;Priority=5
;Waypoint=HZ
;Annoyance=no
;IonImmune=no
;Recruiter=no
;Reinforce=no
;TaskForce=RSTF_DF
;TechLevel=0
;Aggressive=no
;Autocreate=no
;GuardSlower=no
;OnTransOnly=no
;AvoidThreats=no
;LooseRecruit=no
;VeteranLevel=1
;IsBaseDefense=no
;UseTransportOrigin=no
;MindControlDecision=0
;OnlyTargetHouseEnemy=no
;TransportsReturnOnUnload=no
;AreTeamMembersRecruitable=no
;
;[RST18001]
;Max=5
;Tag=RS180002_tag
;Full=no
;Name=[Respawn]No.18
;Group=-1
;House=<Player @ A>
;Script=RSST_DF
;Whiner=no
;Droppod=no
;Suicide=no
;Loadable=no
;Prebuild=no
;Priority=5
;Waypoint=HZ
;Annoyance=no
;IonImmune=no
;Recruiter=no
;Reinforce=no
;TaskForce=RSTF_DF
;TechLevel=0
;Aggressive=no
;Autocreate=no
;GuardSlower=no
;OnTransOnly=no
;AvoidThreats=no
;LooseRecruit=no
;VeteranLevel=1
;IsBaseDefense=no
;UseTransportOrigin=no
;MindControlDecision=0
;OnlyTargetHouseEnemy=no
;TransportsReturnOnUnload=no
;AreTeamMembersRecruitable=no
;
;[RST19001]
;Max=5
;Tag=RS190002_tag
;Full=no
;Name=[Respawn]No.19
;Group=-1
;House=<Player @ A>
;Script=RSST_DF
;Whiner=no
;Droppod=no
;Suicide=no
;Loadable=no
;Prebuild=no
;Priority=5
;Waypoint=HZ
;Annoyance=no
;IonImmune=no
;Recruiter=no
;Reinforce=no
;TaskForce=RSTF_DF
;TechLevel=0
;Aggressive=no
;Autocreate=no
;GuardSlower=no
;OnTransOnly=no
;AvoidThreats=no
;LooseRecruit=no
;VeteranLevel=1
;IsBaseDefense=no
;UseTransportOrigin=no
;MindControlDecision=0
;OnlyTargetHouseEnemy=no
;TransportsReturnOnUnload=no
;AreTeamMembersRecruitable=no
;
;[RST20001]
;Max=5
;Tag=RS200002_tag
;Full=no
;Name=[Respawn]No.20
;Group=-1
;House=<Player @ A>
;Script=RSST_DF
;Whiner=no
;Droppod=no
;Suicide=no
;Loadable=no
;Prebuild=no
;Priority=5
;Waypoint=HZ
;Annoyance=no
;IonImmune=no
;Recruiter=no
;Reinforce=no
;TaskForce=RSTF_DF
;TechLevel=0
;Aggressive=no
;Autocreate=no
;GuardSlower=no
;OnTransOnly=no
;AvoidThreats=no
;LooseRecruit=no
;VeteranLevel=1
;IsBaseDefense=no
;UseTransportOrigin=no
;MindControlDecision=0
;OnlyTargetHouseEnemy=no
;TransportsReturnOnUnload=no
;AreTeamMembersRecruitable=no