; ==================================================
; 红色警戒2 INI片段精炼厂 - 开局资金判断难度，设置局部变量
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[VariableNames];�ֲ�����
90=Difficult Easy
91=Difficult Normal
92=Difficult Hard
[Triggers]
DIFF00=Arabs,<none>,[DifficultTest]Test E,0,1,1,1,0
DIFF02=Arabs,<none>,[DifficultTest]Test N,0,1,1,1,0
DIFF04=Arabs,<none>,[DifficultTest]Test H,0,1,1,1,0
DIFF06=Americans,<none>,[DifficultTest]Delay Ban,0,1,1,1,0
[Actions]
DIFF00=2,56,0,90,0,0,0,0,A,11,4,d1,0,0,0,0,A
DIFF02=2,56,0,91,0,0,0,0,A,11,4,d2,0,0,0,0,A
DIFF04=2,56,0,92,0,0,0,0,A,11,4,d3,0,0,0,0,A
DIFF06=3,54,2,DIFF00,0,0,0,0,A,54,2,DIFF04,0,0,0,0,A,54,2,DIFF02,0,0,0,0,A
[Tags]
DIFF01=0,[DifficultTest]Test E 1,DIFF00
DIFF03=0,[DifficultTest]Test N 1,DIFF02
DIFF05=0,[DifficultTest]Test H 1,DIFF04
DIFF07=0,[DifficultTest]Delay Ban 1,DIFF06
[Events]
DIFF00=1,52,0,10000
DIFF02=2,52,0,20000,12,0,10001
DIFF04=1,12,0,20001
DIFF06=1,13,0,5