; ==================================================
; 红警INI片段百宝箱 - 倒计时剩余时间警告语音
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[Tags]
01TIWA01=2,[z]~[TimerWarning] B. 10 Minutes Remaining 1,01TIWA00
01TIWA03=2,[z]~[TimerWarning] C. 5 Minutes Remaining 1,01TIWA02
01TIWA05=2,[z]~[TimerWarning] D. 4 Minutes Remaining 1,01TIWA04
01TIWA07=2,[z]~[TimerWarning] E. 3 Minutes Remaining 1,01TIWA06
01TIWA09=2,[z]~[TimerWarning] A. 20 Minutes Remaining 1,01TIWA08
01TIWA11=2,[z]~[TimerWarning] F. 2 Minutes Remaining 1,01TIWA10
01TIWA13=2,[z]~[TimerWarning] G. 1 Minute Remaining 1,01TIWA12
01TIWA15=2,[z]~[TimerWarning] Disable All Remaining Warn 1,01TIWA14
[Triggers]
01TIWA00=Americans,<none>,[z]~[TimerWarning]B. 10 Minutes Remaining,1,1,1,1,0
01TIWA02=Americans,<none>,[z]~[TimerWarning]C. 5 Minutes Remaining,1,1,1,1,0
01TIWA04=Americans,<none>,[z]~[TimerWarning]D. 4 Minutes Remaining,1,1,1,1,0
01TIWA06=Americans,<none>,[z]~[TimerWarning]E. 3 Minutes Remaining,1,1,1,1,0
01TIWA08=Americans,<none>,[z]~[TimerWarning]A. 20 Minutes Remaining,1,1,1,1,0
01TIWA10=Americans,<none>,[z]~[TimerWarning]F. 2 Minutes Remaining,1,1,1,1,0
01TIWA12=Americans,<none>,[z]~[TimerWarning]G. 1 Minute Remaining,1,1,1,1,0
01TIWA14=Americans,<none>,[z]~[TimerWarning] Disable All Remaining Warn,1,1,1,1,0
[Actions]
01TIWA00=3,54,2,01TIWA00,0,0,0,0,A,21,6,EVA_10MinutesRemaining,0,0,0,0,A,53,2,01TIWA02,0,0,0,0,A
01TIWA02=3,54,2,01TIWA02,0,0,0,0,A,21,6,EVA_5MinutesRemaining,0,0,0,0,A,53,2,01TIWA04,0,0,0,0,A
01TIWA04=3,54,2,01TIWA04,0,0,0,0,A,21,6,EVA_4MinutesRemaining,0,0,0,0,A,53,2,01TIWA06,0,0,0,0,A
01TIWA06=3,54,2,01TIWA06,0,0,0,0,A,21,6,EVA_3MinutesRemaining,0,0,0,0,A,53,2,01TIWA10,0,0,0,0,A
01TIWA08=3,54,2,01TIWA08,0,0,0,0,A,21,6,EVA_20MinutesRemaining,0,0,0,0,A,53,2,01TIWA00,0,0,0,0,A
01TIWA10=3,54,2,01TIWA10,0,0,0,0,A,21,6,EVA_2MinutesRemaining,0,0,0,0,A,53,2,01TIWA12,0,0,0,0,A
01TIWA12=2,54,2,01TIWA12,0,0,0,0,A,21,6,EVA_1MinuteRemaining,0,0,0,0,A
01TIWA14=8,54,2,01TIWA14,0,0,0,0,A,54,2,01TIWA08,0,0,0,0,A,54,2,01TIWA00,0,0,0,0,A,54,2,01TIWA02,0,0,0,0,A,54,2,01TIWA04,0,0,0,0,A,54,2,01TIWA06,0,0,0,0,A,54,2,01TIWA10,0,0,0,0,A,54,2,01TIWA12,0,0,0,0,A
[Events]
01TIWA00=1,13,0,600
01TIWA02=1,13,0,300
01TIWA04=1,13,0,60
01TIWA06=1,13,0,60
01TIWA08=1,13,0,0
01TIWA10=1,13,0,60
01TIWA12=1,13,0,60
01TIWA14=1,8,0,0