; ==================================================
; 红警INI片段精炼厂 - 沙漠-暗橙色光照
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[Lighting]
Red=1.000000
Blue=0.700000
Green=0.890000
Level=0.000000
Ground=0.000000
IonRed=1.000000
Ambient=0.720000
IonBlue=1.000000
IonGreen=1.000000
IonLevel=0.032000
IonGround=0.000000
IonAmbient=1.000000
DominatorRed=0.850000
DominatorBlue=0.300000
DominatorGreen=0.200000
DominatorLevel=0.000000
DominatorGround=0.000000
DominatorAmbient=1.500000
DominatorAmbientChangeRate=0.009000