; ==================================================
; 红色警戒2 INI片段精炼厂
; 由 cake1 维护 (https://github.com/GlowingCake/-RA2-INI_For_Mappers)
; 许可证：MIT
; ==================================================

;修复官方遗留的一些小问题，不会影响游戏平衡，没有新增弹头或动画的地图可以直接无脑导入，新增了弹头或动画的地图需要看一下下面的注释防止注册号重复。
;修复了[CombatDamage]和[BORIS]修改导致的V3、无畏、雷鸣飞弹3星飞弹异常和鲍里斯3星时召唤的米格战机数量异常。
;绝大部分修复由byx2020更新于2023/03/05，cake1于2026/05/09将其中的部分内容整合到本ini中，有修改。


[General];避免YR环境下地图中修改了General时，光棱塔连接伤害会错误变为150倍
PrismSupportModifier=1.5

[FlakWeaponE];修正原版防空履带车和海蝎的三星对地武器射程比无星对地武器射程短，使其一致
Range=10
[FlakTrackAAGunE];修正原版防空履带车和海蝎的三星对空武器射程比无星对空武器射程短，使其一致
Range=10
[NeutronRifleE];修复超时空军团兵无星武器能穿墙，三星武器反而不能穿墙的问题
Projectile=InvisibleMedium
[CRNeutronRifle];修复超时空军团兵无星时不进入FV能穿墙，进入FV武器反而不能穿墙的问题
Projectile=InvisibleMedium
[SquidPunchE];原版巨型乌贼的三星武器可以对空，此处禁止
Projectile=InvisibleLow
[MirageGunE];修复幻影坦克三星武器开火动画缺失
Anim=VTMUZZLE

[SCHP];武装直升机，解决原版AI不能正常使用和探开黑雾的一些问题
SpeedType=Winged
;原版是Hover
BalloonHover=yes
;原版没有

[CABHUT];使桥梁维修小屋可以免疫超时空攻击
Warpable=no

[AI];在游戏中，中立阵营获得基地车后(中立工程师占了你的基地、尤里控制了敌人的基地车，该阵营失败后解除控制，就变成中立基地)会导致IE，此处修复这个bug，原理详见帖子https://bbs.ra2diy.com/forum.php?mod=viewthread&tid=19875。
BuildPower=NAPOWR,GAPOWR,YAPOWR,CITY01
BuildRefinery=NAREFN,GAREFN,YAREFN,CITY02
BuildBarracks=NAHAND,GAPILE,YABRCK,CITY03
[CITY01];给中立阵营用的假电厂
Owner=Neutral,Special
AIBuildThis=yes
[CITY02];给中立阵营用的假矿厂
Owner=Neutral,Special
AIBuildThis=yes
[CITY03];给中立阵营用的假雷达
Owner=Neutral,Special
AIBuildThis=yes

[Warheads];补充原版中未注册的原版弹头，注册号可以自己调整，注意不要和自己新增的弹头或者原版已注册弹头的注册号(区间1-105)重复了！如果你的地图没有新增弹头，直接导入使用即可。
151=SANoBuilding
152=HollowPoint4
153=GRIZAPE
154=RHINAPE
155=ApocAPE
156=KTSTLEXP
157=MagneShakeWH
158=GrandCannonEWH
159=UltraAPE
160=PrismWarhead
161=Shock
162=MummyBattering
163=DummyWarhead
[Animations];补充原版中未注册的原版动画，注册号可以自己调整，注意不要和自己新增的动画或原版已注册动画的注册号(区间1-1071)重复了！如果你的地图没有新增弹头，直接导入使用即可。
1201=GTPOWEXP
1202=TSTLEXP
1203=APMUZZLE
1204=APOCEXP
1205=YURICNTL
1206=MINDANIMR
1207=WCLBOLT2
1208=GAWETH_ED
1209=GAWETH_GD
1210=SMOKEY2
1211=YAPSYT_B
1212=YAPSYT_BD

[CombatDamage];修复修改[CombatDamage]导致V3、无畏、雷鸣飞弹3星飞弹异常
V3EliteWarhead=V3EWH
DMislEliteWarhead=DMISLEWH
CMislEliteWarhead=CMISLEWH

[BORIS];修复修改[BORIS]导致鲍里斯3星时召唤的米格战机数量异常
EliteAirstrikeTeam=4