; ==================================================
; 红警INI片段百宝箱 - 基地绑间谍卫星效果（开全图，但失去黑全图）
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[GACNST]
Radar=yes
SpySat=yes
[NACNST]
Radar=yes
SpySat=yes
[YACNST]
Radar=yes
SpySat=yes