; ==================================================
; 红色警戒2 INI片段精炼厂 - 延长左上角信息显示时间
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

;原本为0.8分钟
[AudioVisual]
MessageDelay=3