; ==================================================
; 红警INI片段精炼厂 - 建造上限99
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[General]
MaximumQueuedObjects=98