; ==================================================
; 红警INI片段百宝箱 - 开局单次更改所属，位置A到H都有对应触发
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[Events]
CAGAVE00=1,8,0,0
CAGAVE02=1,8,0,0
CAGAVE04=1,8,0,0
CAGAVE06=1,8,0,0
CAGAVE08=1,8,0,0
CAGAVE10=1,8,0,0
CAGAVE12=1,8,0,0
CAGAVE14=1,8,0,0
[Triggers]
CAGAVE00=Americans,<none>,[z]~[SimpleGive] GAVE A,0,1,1,1,0
CAGAVE02=Americans,<none>,[z]~[SimpleGive] GAVE B,0,1,1,1,0
CAGAVE04=Americans,<none>,[z]~[SimpleGive] GAVE C,0,1,1,1,0
CAGAVE06=Americans,<none>,[z]~[SimpleGive] GAVE D,0,1,1,1,0
CAGAVE08=Americans,<none>,[z]~[SimpleGive] GAVE E,0,1,1,1,0
CAGAVE10=Americans,<none>,[z]~[SimpleGive] GAVE F,0,1,1,1,0
CAGAVE12=Americans,<none>,[z]~[SimpleGive] GAVE G,0,1,1,1,0
CAGAVE14=Americans,<none>,[z]~[SimpleGive] GAVE H,0,1,1,1,0
[Tags]
CAGAVE01=0,[z]~[SimpleGive] GAVE A 1,CAGAVE00
CAGAVE03=0,[z]~[SimpleGive] GAVE B 1,CAGAVE02
CAGAVE05=0,[z]~[SimpleGive] GAVE C 1,CAGAVE04
CAGAVE07=0,[z]~[SimpleGive] GAVE D 1,CAGAVE06
CAGAVE09=0,[z]~[SimpleGive] GAVE E 1,CAGAVE08
CAGAVE11=0,[z]~[SimpleGive] GAVE F 1,CAGAVE10
CAGAVE13=0,[z]~[SimpleGive] GAVE G 1,CAGAVE12
CAGAVE15=0,[z]~[SimpleGive] GAVE H 1,CAGAVE14
[Actions]
CAGAVE00=1,14,0,4475,0,0,0,0,A
CAGAVE02=1,14,0,4476,0,0,0,0,A
CAGAVE04=1,14,0,4477,0,0,0,0,A
CAGAVE06=1,14,0,4478,0,0,0,0,A
CAGAVE08=1,14,0,4479,0,0,0,0,A
CAGAVE10=1,14,0,4480,0,0,0,0,A
CAGAVE12=1,14,0,4481,0,0,0,0,A
CAGAVE14=1,14,0,4482,0,0,0,0,A