; ==================================================
; 红色警戒2 INI片段精炼厂
; 创建者：cake1 (https://github.com/GlowingCake/-RA2-INI_For_Mappers)
; 许可证：MIT
; ==================================================

[General]
GrowthRate=1