; ==================================================
; 红警INI片段精炼厂 - 特色单位阵营间共享
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[AMRADR]
RequiredHouses=British,French,Germans,Americans,Alliance

[GAAIRC]
ForbiddenHouses=British,French,Germans,Americans,Alliance

[SNIPE]
RequiredHouses=British,French,Germans,Americans,Alliance

[TNKD]
RequiredHouses=British,French,Germans,Americans,Alliance

[GTGCAN]
RequiredHouses=British,French,Germans,Americans,Alliance

[ORCA]
TechLevel=-1

[BEAG]
RequiredHouses=British,French,Germans,Americans,Alliance

[DTRUCK]
RequiredHouses=Russians,Confederation,Africans,Arabs

[DESO]
RequiredHouses=Russians,Confederation,Africans,Arabs

[TTNK]
RequiredHouses=Russians,Confederation,Africans,Arabs
[TERROR]
RequiredHouses=Russians,Confederation,Africans,Arabs