; ==================================================
; 红色警戒2 INI片段精炼厂 - 生死斗模式YR转RA2（禁用YR科技）
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[YAYARD]
TechLevel=11

[GATECH]
SuperWeapon=none

[NATECH]
SuperWeapon=none

[YATECH]
SuperWeapon=none

[BORIS]
TechLevel=11

[SA]
;CellSpread=.3
;PercentAtMax=.5
Verses=100%,80%,70%,50%,25%,25%,75%,50%,25%,100%,100%
InfDeath=1
AnimList=PIFFPIFF,PIFFPIFF
;Bright=yes
Bullets=yes
ProneDamage=70%

[SSA]
;CellSpread=.3
;PercentAtMax=.5
Verses=100%,100%,70%,60%,40%,40%,75%,50%,25%,100%,100%
InfDeath=1
AnimList=PIFFPIFF,PIFFPIFF
;Bright=yes
Bullets=yes
ProneDamage=50%

[HARVWH]
;CellSpread=.3
;PercentAtMax=.5
Verses=100%,80%,70%,50%,20%,20%,20%,15%,10%,200%,100%
InfDeath=1
AnimList=PIFFPIFF,PIFFPIFF
;Bright=yes
Bullets=yes
ProneDamage=50%

[FlakTrackGunE]		; Anti-surface gun
Damage=25
ROF=40
Range=5
Projectile=FlakTProj
Speed=50
Report=FlakTrackAttackGround		; put in new sound for this
Warhead=FlakTWH
Anim=GUNFIRE
Burst=2

[FlakTrackGun]		; Anti-surface gun
Damage=25
ROF=40
Range=5
Projectile=FlakTProj
Speed=50
Report=FlakTrackAttackGround		; put in new sound for this
Warhead=FlakTWH
Anim=GUNFIRE

[FlakTrackAAGun]	; Separate from Flak Cannon weapon so that stats may be tweaked
Damage=35
ROF=25
Range=10
Projectile=FlakProj	; AA bullet shared with Flak Cannon
Speed=100
Report=FlakTrackAttackAir
Warhead=FlakWH
Anim=GUNFIRE

[FlakTrackAAGunE]	; Separate from Flak Cannon weapon so that stats may be tweaked
Damage=20
ROF=25
Range=8
Projectile=FlakProj	; AA bullet shared with Flak Cannon
Speed=100
Report=FlakTrackAttackAir
Warhead=FlakWH
Anim=GUNFIRE
Burst=2

[FlakGuyAAGunE]	; Separate from Flak Cannon weapon so that stats may be tweaked
Damage=18
ROF=25
Range=8
Projectile=FlakProj	; AA bullet shared with Flak Cannon
Speed=100
Report=FlakTrackAttackAir
Warhead=FlakGuyWH
Anim=GUNFIRE
Burst=2

[M60E]
Damage=25
ROF=20
Range=4
Projectile=InvisibleLow
Speed=100
Warhead=SA
Report=GIAttack
Anim=MGUN-N,MGUN-NE,MGUN-E,MGUN-SE,MGUN-S,MGUN-SW,MGUN-W,MGUN-NW

[Para]
Damage=15
ROF=15
Range=5

[GHOST]
TechLevel=11

[GGI]
TechLevel=11

[BFRT]
TechLevel=11

[SCHP]
TechLevel=11

[GAROBO]
TechLevel=11

[NABNKR]
TechLevel=11

[NAINDP]
TechLevel=11

[NACLON]
Prerequisite=NACNST,NATECH
Owner=Russia‎ns,Confed‎eratio‎n,Africa‎ns,Arabs,Britis‎h,French,German‎s,Americ‎ans,Allian‎ce,YuriCountry

[YURI]
Prerequisite=NAHAND,NATECH
Owner=Russia‎ns,Confed‎eratio‎n,Africa‎ns,Arabs,Britis‎h,French,German‎s,Americ‎ans,Allian‎ce,YuriCountry

[MTNK]
BuildTimeMultiplier=1

[HTNK]
BuildTimeMultiplier=1

[TTNK]
BuildTimeMultiplier=1

[APOC]
BuildTimeMultiplier=1

[NAPSIS]
TechLevel=10
Owner=British,French,Germans,Americans,Alliance,Russians,Confederation,Africans,Arabs
Prerequisite=NATECH,NACNST
Spyable=no
SuperWeapon=none

;禁用尤里复仇单位