; ==================================================
; 红色警戒2 INI片段精炼厂 - 矿很难采完，钱不变吸的速度变快
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

; This is Ore
[Riparius]
Name=Tiberium Riparius
Image=1
Power=0
Value=5;25
Growth=2200
GrowthPercentage=.06
Spread=2200
SpreadPercentage=.06
Color=NeonGreen			; **WARNING**: If you change this color, notify Bret_a
; These are Gems
[Cruentus]
Name=Tiberium Cruentus
Image=2
Value=10;50
Growth=10000
GrowthPercentage=0
Spread=10000
SpreadPercentage=0
Power=0 ;10
Color=NeonBlue			; **WARNING**: If you change this color, notify Bret_a
Debris=CRYSTAL1,CRYSTAL2,CRYSTAL3,CRYSTAL4
[HARV]
Storage=8;40
[CMIN]
Storage=4;20
[SLAV];无法修改，禁止尤里出现。