; ==================================================
; 红色警戒2 INI片段精炼厂
; 创建者：cake1 (https://github.com/GlowingCake/-RA2-INI_For_Mappers)
; 许可证：MIT
; ==================================================

[V3]
TechLevel=11
[NATECH]
TechLevel=11
[TESLA]
TechLevel=11
[IVAN]
TechLevel=11
[ATESLA]
TechLevel=11
[JUMPJET]
TechLevel=11
[GHOST]
TechLevel=11
[GATECH]
TechLevel=11
[GAROBO]
TechLevel=11
[ORCA]
TechLevel=11
[SMCV]
TechLevel=11
[AMCV]
TechLevel=11