; ==================================================
; 红色警戒2 INI片段精炼厂 - 苏盟作战转生死斗(生死斗模式打乱科技点数，这时可考虑伪生死斗）
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[V3]
TechLevel=11
[NATECH]
TechLevel=11
[TESLA]
TechLevel=11
[IVAN]
TechLevel=11
[ATESLA]
TechLevel=11
[JUMPJET]
TechLevel=11
[GHOST]
TechLevel=11
[GATECH]
TechLevel=11
[GAROBO]
TechLevel=11
[ORCA]
TechLevel=11
[SMCV]
TechLevel=11
[AMCV]
TechLevel=11