; ==================================================
; 红色警戒2 INI片段精炼厂
; 创建者：cake1 (https://github.com/GlowingCake/-RA2-INI_For_Mappers)
; 许可证：MIT
; ==================================================

[AMRADR]
RequiredHouses=British,French,Germans,Americans,Alliance

[GAAIRC]
ForbiddenHouses=British,French,Germans,Americans,Alliance

[SNIPE]
RequiredHouses=British,French,Germans,Americans,Alliance

[TNKD]
RequiredHouses=British,French,Germans,Americans,Alliance

[GTGCAN]
RequiredHouses=British,French,Germans,Americans,Alliance

[ORCA]
TechLevel=-1

[BEAG]
RequiredHouses=British,French,Germans,Americans,Alliance

[DTRUCK]
RequiredHouses=Russians,Confederation,Africans,Arabs

[DESO]
RequiredHouses=Russians,Confederation,Africans,Arabs

[TTNK]
RequiredHouses=Russians,Confederation,Africans,Arabs
[TERROR]
RequiredHouses=Russians,Confederation,Africans,Arabs