; ==================================================
; 红警INI片段百宝箱 - 五倍矿棒效率（解决人多矿不够问题）
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[General]
GrowthRate=1