; ==================================================
; 红色警戒2 INI片段精炼厂 - 开局改所属A到H延迟3秒（防AI展开基地拉兵）
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[Events]
CAGAVED00=1,13,0,3
CAGAVED02=1,13,0,3
CAGAVED04=1,13,0,3
CAGAVED06=1,13,0,3
CAGAVED08=1,13,0,3
CAGAVED10=1,13,0,3
CAGAVED12=1,13,0,3
CAGAVED14=1,13,0,3
[Triggers]
CAGAVED00=Americans,<none>,[z]~[SimpleGiveDelay3s] GAVE A,0,1,1,1,0
CAGAVED02=Americans,<none>,[z]~[SimpleGiveDelay3s] GAVE B,0,1,1,1,0
CAGAVED04=Americans,<none>,[z]~[SimpleGiveDelay3s] GAVE C,0,1,1,1,0
CAGAVED06=Americans,<none>,[z]~[SimpleGiveDelay3s] GAVE D,0,1,1,1,0
CAGAVED08=Americans,<none>,[z]~[SimpleGiveDelay3s] GAVE E,0,1,1,1,0
CAGAVED10=Americans,<none>,[z]~[SimpleGiveDelay3s] GAVE F,0,1,1,1,0
CAGAVED12=Americans,<none>,[z]~[SimpleGiveDelay3s] GAVE G,0,1,1,1,0
CAGAVED14=Americans,<none>,[z]~[SimpleGiveDelay3s] GAVE H,0,1,1,1,0
[Tags]
CAGAVED01=0,[z]~[SimpleGiveDelay3s] GAVE A 1,CAGAVE00
CAGAVED03=0,[z]~[SimpleGiveDelay3s] GAVE B 1,CAGAVE02
CAGAVED05=0,[z]~[SimpleGiveDelay3s] GAVE C 1,CAGAVE04
CAGAVED07=0,[z]~[SimpleGiveDelay3s] GAVE D 1,CAGAVE06
CAGAVED09=0,[z]~[SimpleGiveDelay3s] GAVE E 1,CAGAVE08
CAGAVED11=0,[z]~[SimpleGiveDelay3s] GAVE F 1,CAGAVE10
CAGAVED13=0,[z]~[SimpleGiveDelay3s] GAVE G 1,CAGAVE12
CAGAVED15=0,[z]~[SimpleGiveDelay3s] GAVE H 1,CAGAVE14
[Actions]
CAGAVED00=1,14,0,4475,0,0,0,0,A
CAGAVED02=1,14,0,4476,0,0,0,0,A
CAGAVED04=1,14,0,4477,0,0,0,0,A
CAGAVED06=1,14,0,4478,0,0,0,0,A
CAGAVED08=1,14,0,4479,0,0,0,0,A
CAGAVED10=1,14,0,4480,0,0,0,0,A
CAGAVED12=1,14,0,4481,0,0,0,0,A
CAGAVED14=1,14,0,4482,0,0,0,0,A