; ==================================================
; 红色警戒2 INI片段精炼厂 - 开局改所属A到H延迟5分钟（用于给AI启用额外建筑，太早玩家打不了）
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[Events]
CAGAVEDB00=1,13,0,300
CAGAVEDB02=1,13,0,300
CAGAVEDB04=1,13,0,300
CAGAVEDB06=1,13,0,300
CAGAVEDB08=1,13,0,300
CAGAVEDB10=1,13,0,300
CAGAVEDB12=1,13,0,300
CAGAVEDB14=1,13,0,300
[Triggers]
CAGAVEDB00=Americans,<none>,[z]~[SimpleGiveDelay5Min] GAVE A,0,1,1,1,0
CAGAVEDB02=Americans,<none>,[z]~[SimpleGiveDelay5Min] GAVE B,0,1,1,1,0
CAGAVEDB04=Americans,<none>,[z]~[SimpleGiveDelay5Min] GAVE C,0,1,1,1,0
CAGAVEDB06=Americans,<none>,[z]~[SimpleGiveDelay5Min] GAVE D,0,1,1,1,0
CAGAVEDB08=Americans,<none>,[z]~[SimpleGiveDelay5Min] GAVE E,0,1,1,1,0
CAGAVEDB10=Americans,<none>,[z]~[SimpleGiveDelay5Min] GAVE F,0,1,1,1,0
CAGAVEDB12=Americans,<none>,[z]~[SimpleGiveDelay5Min] GAVE G,0,1,1,1,0
CAGAVEDB14=Americans,<none>,[z]~[SimpleGiveDelay5Min] GAVE H,0,1,1,1,0
[Tags]
CAGAVEDB01=0,[z]~[SimpleGiveDelay5Min] GAVE A 1,CAGAVE00
CAGAVEDB03=0,[z]~[SimpleGiveDelay5Min] GAVE B 1,CAGAVE02
CAGAVEDB05=0,[z]~[SimpleGiveDelay5Min] GAVE C 1,CAGAVE04
CAGAVEDB07=0,[z]~[SimpleGiveDelay5Min] GAVE D 1,CAGAVE06
CAGAVEDB09=0,[z]~[SimpleGiveDelay5Min] GAVE E 1,CAGAVE08
CAGAVEDB11=0,[z]~[SimpleGiveDelay5Min] GAVE F 1,CAGAVE10
CAGAVEDB13=0,[z]~[SimpleGiveDelay5Min] GAVE G 1,CAGAVE12
CAGAVEDB15=0,[z]~[SimpleGiveDelay5Min] GAVE H 1,CAGAVE14
[Actions]
CAGAVEDB00=1,14,0,4475,0,0,0,0,A
CAGAVEDB02=1,14,0,4476,0,0,0,0,A
CAGAVEDB04=1,14,0,4477,0,0,0,0,A
CAGAVEDB06=1,14,0,4478,0,0,0,0,A
CAGAVEDB08=1,14,0,4479,0,0,0,0,A
CAGAVEDB10=1,14,0,4480,0,0,0,0,A
CAGAVEDB12=1,14,0,4481,0,0,0,0,A
CAGAVEDB14=1,14,0,4482,0,0,0,0,A