; ==================================================
; 红警INI片段百宝箱 - 科技电厂增强（给AI免除后顾之忧）
; 作者：cake1
; GitHub：GlowingCake (https://github.com/GlowingCake)
; 创建日期：2026-04-10
; 许可证：MIT (详见仓库 LICENSE 文件)
; ==================================================

[CAPOWR]
Power=2000
Strength=2000