; ==================================================
; 红色警戒2 INI片段精炼厂
; 由 cake1 维护 (https://github.com/GlowingCake/-RA2-INI_For_Mappers)
; 许可证：MIT
; ==================================================

[HTNK]
BuildTimeMultiplier=1.0
[MTNK]
BuildTimeMultiplier=1.0
[LTNK]
BuildTimeMultiplier=1.0