;= 任务目标模板CSF文件 作者cake1 作者GitHub：GlowingCake (https://github.com/GlowingCake)
;= 任务一相关消息
ob1In0=【任务一介绍：开始第一个任务目标时显示】
ob1Complete=【任务目标一完成时显示的消息】
;Ob1failed0=【任务目标一失败时显示的原因】
ob1=任务目标一：【任务目标内容】
;= 任务二相关消息
ob2In0=【任务二介绍：开始第二个任务目标时显示】
ob2Complete=【任务目标二完成时显示的消息】
;Ob2failed0=【任务目标二失败时显示的原因】
ob2=任务目标二：【任务目标内容】
;= 任务三相关消息
ob3In0=【任务三介绍：开始第三个任务目标时显示】
ob3Complete=【任务目标三完成时显示的消息】
;Ob3failed0=【任务目标三失败时显示的原因】
ob3=任务目标三：【任务目标内容】
;= 任务四相关消息
ob4In0=【任务四介绍：开始第四个任务目标时显示】
ob4Complete=【任务目标四完成时显示的消息】
;Ob4failed0=【任务目标四失败时显示的原因】
ob4=任务目标四：【任务目标内容】
;= 任务五相关消息
ob5In0=【任务五介绍：开始第五个任务目标时显示】
ob5Complete=【任务目标五完成时显示的消息】
;Ob5failed0=【任务目标五失败时显示的原因】
ob5=任务目标五：【任务目标内容】
;= 任务完成消息
MissionAccomplished=【任务完成！你成功完成了所有任务目标！】